### ISSUE TITLE
auto-complete doesn't work

### ISSUE THREAD

**Issue by toolboxen** [renerocksai/sublime_zk#18] opened 2017-11-04 08:40 UTC
The last remaining bug I found 😄 but `ctrl+space` does nothing, not even throw an error to the console. Investigating to see what the issue is.

**Comment by renerocksai** [comment] 2017-11-04 10:12
well, did it ever? is this a regression? does it work with other syntaxes?

if yes, then it must be this plugin. based on recent experience, having no
path might cause that.
another candidate might be: your files don't end in `md` but the setting
`wiki_extension` is set to `.md`

maybe it is fixed now because `get_path_for(view)` is used almost
everywhere?

can you describe in which situation it's not working? like: even within a
project?

**Comment by renerocksai** [comment] 2017-11-04 10:13
well, did it ever? is this a regression? does it work with other syntaxes?

if yes, then it must be this plugin. based on recent experience, having no
path might cause that.
another candidate might be: your files don't end in `md` but the setting
`wiki_extension` is set to `.md`

maybe it is fixed now because `get_path_for(view)` is used almost
everywhere?

can you describe in which situation it's not working? like: even within a
project?

**Comment by renerocksai** [comment] 2017-11-04 10:16
Or maybe it bombs out (in `on_query_completions()`) at:

```python
        if view.match_selector(point, 'text.html.markdown') == 0:
            return
```

Maybe for some strange reason the text under your cursor has no `text.html.markdown` scope?

**Comment by toolboxen** [comment] 2017-11-04 10:20
Sorry for my vagueness in the original post. I've got some better details now!

So I have setup a project `notes` and saved the project correctly inside the folder. with a `notes.sublime-project` all my notes are `.md` files and upon triggering command with `ctrl+space` the console throws the following:

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 591, in on_query_completions
    res = callback.on_query_completions(v, prefix, locations)
  File "C:\Users\user\AppData\Roaming\Sublime Text 3\Packages\sublime_zk\sublime_zk.py", line 236, in on_query_completions
    for noteid, notename in ids_and_names:
ValueError: need more than 1 value to unpack
```

**Comment by renerocksai** [comment] 2017-11-04 10:25
awesome! we're getting there! btw your path checks from NewZettelCommand
broke it for empty window. i hadn't noticed it when checking the commits.
but it's fixed now in master.

I'll have a look at your error now

**Comment by toolboxen** [comment] 2017-11-04 10:28
>btw your path checks from NewZettelCommand broke it for empty window.

grrrr... `/facepalm` -- i see your fix now, makes total sense.

**Comment by renerocksai** [comment] 2017-11-04 10:32
No worries, happens to the best :P

You must have something strange in your folder. Maybe it's the wrong folder.
So better put a `print(folder)` after the `get_path_for(view)` to make sure it's the right one.

But what's causing the error is:

```python
        ids_and_names = [f.split(' ', 1) for f in os.listdir(folder)
                                            if f.endswith(extension)]
```
This is supposed to collect all `.md` files and split them into **two** parts: The one before the first space (the ID) and the one after the first space (the title). Do you have an `.md` in there that somehow causes `'my bad file.md'.split(' ', 1)` to return not two but only **one** item?

OMG! Wouldn't a `README.md` cause that?

Must check that.....

**Comment by toolboxen** [comment] 2017-11-04 10:35
AHA -- this folder doesn't have a readme BUT it does have a single `test.md` while all the other file names are `NOTEID TITLESTRINGS.md` format. deleting `test.md` fixes it and now i have autocompletions

**Comment by renerocksai** [comment] 2017-11-04 10:36
Yep, that was it :)

Fixed in master:

```python
        ids_and_names = [f.split(' ', 1) for f in os.listdir(folder)
                                            if f.endswith(extension)
                                            and ' ' in f]
```

**Closed** 2017-11-04 10:38 UTC

**Comment by toolboxen** [comment] 2017-11-04 10:40
it's a fix! although the plugin is now completely ignoring `test.md` which is fine.

as an aside, auto-completions seem to work the same as the overlay. they both display all the notes, they both fuzzy filter the same, and i can scroll with my mouse through both exactly the same. Is there any reason the overlay is preferred over the completions menu? Is it just that `[` doesn't trigger correctly?

**Comment by toolboxen** [comment] 2017-11-04 10:50
actually I found your comment here: https://github.com/renerocksai/sublime_zk/issues/3#issuecomment-341834866 so that makes sense.

I just realized that autocomplete has another annoying disadvantage in comparison to the overlay: pressing spacebar chooses an autocomplete selection. but I often press space when typing note titles! Can it be changed? Yes, but not easily: 

- https://forum.sublimetext.com/t/stop-auto-complete-from-committing-on-space/15104/4
- https://stackoverflow.com/questions/30335257/sublime-text-3-stop-auto-complete-from-committing-on-space

I think your choice of relying on the overlay, and not auto-triggering completions upon `[` make sense.

**Comment by renerocksai** [comment] 2017-11-04 10:51
I consider ignoring `test.md` correct since it is not a "Zettelkasten note". No ID can be retrieved from this filename and put into a note link for reference. Allowing `[test]` to open `test.md`, yeah, I can see the point, but for me it's a moot one since this is a rather specific plugin. `[test.md]` is also not supported by the underliner, ...

* Overlay is not preferred per se. But I prefer it a bit.
* The main reason it's not bound to `[[` is because I can't get it to work with that `auto_`... setting that one should not mess with. Re-implementing that feature so that it works in all conditions is tricky, especially when (multiple) selections come into play and I bet there will be other cases I can't even think of at the moment that would ... disappoint... users when not done right.
* They **don't** fuzzy filter the same. Auto-complete is far more strict as it seems. When I type `predi` into my auto-complete, I get 2 fuzzy matches. With the overlay I get **10!**
* As I mentioned earlier, auto-complete disappears, leaving you with nothing useful once you type one character too much. This makes searching by trial-and-error infeasible. The overlay might not show suggestions but at least the search mask stays there and let's you paddle back and change your search term(s)

Oh, now you were quicker :)

**Comment by toolboxen** [comment] 2017-11-04 11:05
> I consider ignoring test.md correct since it is not a "Zettelkasten note".

agreed.

> Overlay is not preferred per se. But I prefer it a bit.

it's not too bad. breaks the flow of writing a little but that's a nitpick on my part.

> They don't fuzzy filter the same. Auto-complete is far more strict as it seems. When I type predi into my auto-complete, I get 2 fuzzy matches. With the overlay I get 10!

What? weird... that behaviour makes no sense. I've not encountered a situation like that before. Why would they be at all different? Maybe is it how you are getting the files? Just to check, is the completion popup being populated by the plugin with exactly the same content as the overlay?

> As I mentioned earlier, auto-complete disappears,

Right, but I thought there might be a way to customize the popup by passing an arg from within the plugin, but on further inspection it seems the completions system really has very little customization options. A shame.

**Comment by renerocksai** [comment] 2017-11-04 11:17
:) Yes they're populated the same. Only in the overlay I don't check for spaces. Actually, it inserts [[README]] and the link can be followed by ctrl+enter because there I just look for the text before the 1st space and treat it as ID and append `.md` :). It just doesn't get caught by the syntax and highligher. Quite right so, I would not encourage this.

A difference I see is that the overlay shows "YYYYMMDDHHmm Periodische...." when I enter `predict`. No letter in that result is bold. So the overlay adaptively also shows candidates, I don't know, because they also start with 'P' in this case and have enough similar letters in them... When I enter just `predic` I get an additional 'YYYYMMDDHHmm Wozu Projektmanagement in der Forschung?", and so on.

The completions pop-up is a beast of its own. I just populate it with all the file names (and IDs as 'second column') and it takes it from there. Strange that it filters differently to the overlay.

**Comment by toolboxen** [comment] 2017-11-04 11:20
Interesting. I admit I don't know enough about how Sublime does fuzzy matching. I guess the completions matching is stricter, but I'm curious what the rationale the Sublime devs might offer as to why they even have a difference?
