### ISSUE TITLE
[[ - To get a list of references to other notes doesn't work. 

### ISSUE THREAD

**Issue by jonathan-s** [renerocksai/sublime_zk#54] opened 2018-03-18 22:09 UTC
When I type in ``[[`` nothing appears at all. So that appears broken? Or rather in my sublime text, what happens is rather that after two ``[[`` the result is the following ``[[]``. Collision with some other plugin?

**Comment by renerocksai** [comment] 2018-03-18 22:14
Collision with another plugin could be the case. But I'd first check something else:

Just some basic checks:

* do you have a project set up?
    * created notes with shift+enter?
* your syntax is set to `Markdown Zettelkasten`?

Now, to see whether the plugin is in trouble, 

* View -> Show Console
* then press `[[`

... and see if it prints out some sort of error message..?

**Comment by jonathan-s** [comment] 2018-03-18 22:20
Project is set up. Ie there is a zettelkasten.sublime-project. The file itself is empty though. I'm able to create a new note with shift+enter. The syntax is also set to Markdown zettelkasten. 

When watching the console while doing ``[[`` nothing appears in the console...

**Comment by renerocksai** [comment] 2018-03-18 23:10
the 2 reasons for nothing happening after `[[`:

* the project path cannot be worked out 
* the key bindings don't work (another plugin interferes?)

Let's try this: Add the following line to `sublime_zk.sublime-commands` (in your package's folder) right before the closing `]`:

```
    { "caption": "ZK: Insert Link", "command": "zk_get_wiki_link" },
```

so it ends with:

```
    { "caption": "ZK: Remove Heading Numbers", "command": "zk_denumber_headings" },
    { "caption": "ZK: Select Panes for opening notes/results", "command": "zk_select_panes" },
    { "caption": "ZK: Insert Link", "command": "zk_get_wiki_link" },
]
```

Or just get the latest version of the package as I have just pushed this change to GitHub.

Then try running the `ZK: Insert Link` command from the command palette (cmd+shift+p / ctrl+shift+p depending on mac or not) while you are in a note you created.

If it works then, then you know it is the key bindings.

**Comment by jonathan-s** [comment] 2018-03-19 18:26
Yeah inserting the link that way works, so it's the key-binding.

**Comment by renerocksai** [comment] 2018-03-19 19:06
That's still a bummer. I wonder if it's easy to work out which plugin is eating away at your `[[`s. I just read [here](http://www.sublimetext.com/docs/key-bindings):

> When the same key is bound multiple times, ordering matters to determine which binding takes precedence. First, the keymap files are sorted by path name, and loaded in that order. Bindings within a file are loaded in the order given in the file. Later bindings overwrite newer bindings.

So, theoretically, you could try renaming your `sublime_zk` folder to `0sublime_zk`, re-start SublimeText, and see if your `[[` starts to work...

**Comment by jonathan-s** [comment] 2018-03-19 19:33
Did some more research. There is package that can find conflicts `FindKeyConflicts`, it details the conflict there. Though the conflict seems to originate from Sublime itself? `setting.auto_match_enabled` which would pair your anchor with the opposite. :
I also found [this][1], that you can have scope for your commands. There is another package called scopehunter which details what scope you currently have. So I tried changing the scope to `text.html.markdown.multimarkdown`. But no luck... 

Weird that even if you set a specific scope like that it doesn't work out. 

[1]: https://forum.sublimetext.com/t/syntax-specific-key-binding/5344/2

**Comment by renerocksai** [comment] 2018-03-19 19:44
Scoping the key bindings of sublime_zk won't work as something else seems to consume the keys before sublime_zk gets asked. If you look at shift+enter, I use a dummy context "sublime_zk" that I had to define within the plugin - you could try that, too (but I doubt it will make a difference for the same reasons I mentioned before): `{ "keys": ["[", "["], "command": "zk_get_wiki_link"}, "context": [ { "key": "sublime_zk", "operand": "true"}] },`.

My `auto_match_enabled` is set to `true`, without any problems. 

You must have something weird going on. You could try to add/redefine a key binding with `]]` if hunting for the root cause is just too much of a pain. Have you tried renaming the plugin folder to something that comes very late in the alphabet?

**Comment by renerocksai** [comment] 2018-03-22 20:47
I am closing this now as it seems to be originating from your setup / plugin situation and not to be a bug of sublime_zk. Feel free to re-open if you think this is wrong.

**Closed by renerocksai** 2018-03-22 20:47 UTC
